[project]
name = "etha"
version = "0.1.0"
description = "etha"
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.10"
dependencies = ["torch"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.build.targets.wheel]
packages = ["src/etha"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["I", "F", "B", "UP"]

[tool.ruff.lint.isort]
length-sort = true
length-sort-straight = true
