"""Batch state management for TensorBus.

A batch represents one call to register_tensors(). Multiple batches can exist
for the same pair, each with independent tensors and handlers.
"""

import torch
import msgspec

from etha.comm.ir import Bucket, SourceChunk, TargetChunk


class BatchState(msgspec.Struct):
    """State for a single batch of registered tensors.

    A batch is created for each register_tensors() call and contains all
    tensor data and execution plans for that specific registration.

    Key design: chunks and buckets are FLATTENED across all pairs in the batch,
    allowing single-pass execution via execute_bucket_pipeline().
    """

    batch_id: str  # UUID generated by client
    pair_names: list[str]  # Which pairs are involved in this batch

    # Data layer: Per-pair organization (for fallback and debugging)
    pair_tensors: dict[str, list[torch.Tensor]] = msgspec.field(default_factory=dict)
    pair_target_dtypes: dict[str, list[torch.dtype]] = msgspec.field(default_factory=dict)

    # Execution layer: FLATTENED across all pairs for efficient execution
    send_chunks: list[SourceChunk | TargetChunk] = msgspec.field(default_factory=list)
    recv_chunks: list[SourceChunk | TargetChunk] = msgspec.field(default_factory=list)
    send_buckets: list[Bucket] | None = None
    recv_buckets: list[Bucket] | None = None

    # Configuration
    bucket_size: int | None = None
