"""Batch state management for TensorBus.

A batch represents one call to register_tensors(). Multiple batches can exist
for the same pair, each with independent tensors and handlers.
"""

import torch
import msgspec
import torch.distributed as dist

from etha.comm.ir import Bucket


class BatchState(msgspec.Struct):
    """State for a single batch of registered tensors.

    A batch is created for each register_tensors() call and contains all
    tensor data and execution plans for that specific registration.

    Key design: buckets are FLATTENED across all pairs in the batch, allowing
    single-pass execution via bucket_comm().
    """

    batch_id: str  # UUID generated by client
    pair_names: list[str]  # Which pairs are involved in this batch

    # Leader coordination for batch-level operations
    local_leader: int | None = None  # local_ranks[0], set during registration
    local_group: dist.ProcessGroup | None = None  # shared local_group, set during registration
    batch_group: dist.ProcessGroup | None = None  # all ranks in batch (local + remote across all pairs)

    # Data layer: Per-pair organization (for fallback and debugging)
    pair_tensors: dict[str, list[torch.Tensor]] = msgspec.field(default_factory=dict)
    pair_target_dtypes: dict[str, list[torch.dtype]] = msgspec.field(default_factory=dict)

    # Execution layer: FLATTENED across all pairs for efficient execution
    send_buckets: list[Bucket] | None = None
    recv_buckets: list[Bucket] | None = None

    # Configuration
    bucket_size: int | None = None
