"""Batch state management for TensorBus.

A batch represents one call to register_tensors(). Multiple batches can exist
for the same pair, each with independent tensors and handlers.
"""

from dataclasses import field, dataclass

import torch
import torch.distributed as dist

from etha.comm.ir import Bucket


@dataclass(kw_only=True)
class BatchState:
    """Runtime state for a single batch of registered tensors, held on the Agent.

    Created per register_tensors() call. Holds live tensors, process-group
    handles, and execution plans (buckets with CUDA work) — in-memory only.

    Key design: buckets are FLATTENED across all pairs in the batch, allowing
    single-pass execution via bucket_comm().
    """

    batch_id: str  # UUID generated by client
    pair_names: list[str]  # Which pairs are involved in this batch

    # Leader coordination for batch-level operations
    local_leader: int | None = None  # local_ranks[0], set during registration
    local_group: dist.ProcessGroup | None = None  # shared local_group, set during registration
    batch_group: dist.ProcessGroup | None = None  # all ranks in batch (local + remote across all pairs)

    # Data layer: Per-pair organization (for fallback and debugging)
    pair_tensors: dict[str, list[torch.Tensor]] = field(default_factory=dict)
    pair_target_dtypes: dict[str, list[torch.dtype]] = field(default_factory=dict)

    # Execution layer: FLATTENED across all pairs for efficient execution
    send_buckets: list[Bucket] | None = None
    recv_buckets: list[Bucket] | None = None

    # Configuration
    bucket_size: int | None = None
